export const USER_STATUS = {
	APPLIED: 'APPLIED',
	INTERVIEWING: 'INTERVIEWING',
	HIRED: 'HIRED',
};

export const STATUS_CHANGE_ACTIONS = {
	BACK: 'BACK',
	FORWARD: 'FORWARD',
};

export const FILTER_TYPE = {
	NAME: 'NAME',
	CITY: 'CITY',
};
